---
# ~/.halation/config.yml (or selectable with a command line flag)
artist: "Me"
copyright: "#{year} Me"
cameras:
  - tag: "rz67"
    make: "Mamiya"
    model: "Mamiya RZ67 Pro II"
    lenses:
      - tag: 65
        model: "M65mm f/4L-A"
        focal_length: 65 # specify for prime lenses
      - tag: 110
        model: "Z110mm f/2.8W"
        focal_length: 110
      - tag: 180
        model: "Z180mm f/4.5W-N"
        focal_length: 180
      - tag: 250
        model: "Z250mm f/4.5W"
        focal_length: 250

---
# roll.yml - placed in the directory containing the images for this roll
artist: "Me" # overridden
copyright: "2016 Me" # overridden
date: "2016-01-01" # default
camera: "rz67"
lens: 110 # default
iso: 100
frames:
  - number: 1
    date: "2016-01-02" # overridden
    lens: 250 # overridden
    shutter: 250 # interpreted as 1/250 -- then how does it know what 25s is? by the "s"?
    aperture: 8
    flash: no
    orientation: "todo (4 options)"
  - number: 2
    lens: "24-70"
    focal_length: 50 # zoom lens has no default focal length
    shutter: 0.5
    aperture: 8
  - number: 3
    shutter: 250
    aperture: 8
  - number: 4
    shutter: 250
    aperture: 8
  - number: 5
    shutter: 250
    aperture: 8
  - number: 6
    shutter: 250
    aperture: 8
  - number: 7
    shutter: 250
    aperture: 8
  - number: 8
    shutter: 250
    aperture: 8
  - number: 9
    shutter: 250
    aperture: 8
  - number: 10
    shutter: 250
    aperture: 8
